'use Client'
import './globals.css'
import Script from "next/script";
import { Inter } from 'next/font/google'
import type { Metadata } from 'next';
import Navbar from './components/Navbar';
import { Providers } from './providers'
import Overlay from './components/overlay/overlay'
import Overlay2 from './components/overlay/overlay2'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Yasir Portfolio',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
     
   
       
      <body className={inter.className}>
      <Script src="https://cdn.tailwindcss.com?plugins=typography"></Script>
      <Providers>
         <Navbar />

        {children}
        <Overlay />
      <Overlay2 />
      </Providers>
        </body>
      
    
    </html>
  )
}
